-- MySQL Script generated by MySQL Workbench
-- 11/29/17 16:15:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema afcontrol
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema afcontrol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `afcontrol` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `afcontrol` ;

-- -----------------------------------------------------
-- Table `afcontrol`.`afiliado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afcontrol`.`afiliado` (
  `idafiliado` INT(11) NOT NULL AUTO_INCREMENT,
  `identificacion` VARCHAR(25) NULL DEFAULT NULL,
  `tipo_identificacion` VARCHAR(45) NULL DEFAULT NULL,
  `nombres` VARCHAR(60) NULL DEFAULT NULL,
  `apellidos` VARCHAR(60) NULL DEFAULT NULL,
  `correo` VARCHAR(70) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `tipo_sanguineo` VARCHAR(25) NULL DEFAULT NULL,
  `telefono` VARCHAR(25) NULL DEFAULT NULL,
  `movil` INT(45) NULL DEFAULT NULL,
  `talla` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `entidad_salud` VARCHAR(60) NULL DEFAULT NULL,
  `tipo_registro` VARCHAR(45) NOT NULL,
  `estado_activo` TINYINT(1) NULL DEFAULT '1',
  `morageneral` TINYINT(1) NULL DEFAULT '0',
  `fecha_registro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idafiliado`),
  UNIQUE INDEX `identificacion_UNIQUE` (`identificacion` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `afcontrol`.`afiliado_contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afcontrol`.`afiliado_contacto` (
  `idafiliado_contacto` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_ref` VARCHAR(60) NULL DEFAULT NULL,
  `telefono_ref` VARCHAR(25) NULL DEFAULT NULL,
  `parentesco_ref` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_registro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `afiliado_idafiliado` INT(11) NOT NULL,
  PRIMARY KEY (`idafiliado_contacto`, `afiliado_idafiliado`),
  INDEX `fk_contacto_afiliado1_idx` (`afiliado_idafiliado` ASC),
  CONSTRAINT `fk_contacto_afiliado1`
    FOREIGN KEY (`afiliado_idafiliado`)
    REFERENCES `afcontrol`.`afiliado` (`idafiliado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `afcontrol`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afcontrol`.`documento` (
  `iddocumento` INT(11) NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(100) NULL DEFAULT NULL,
  `ruta` VARCHAR(120) NULL DEFAULT NULL,
  `tipo` TINYINT(1) NULL DEFAULT NULL,
  `estado` TINYINT(1) NULL DEFAULT '1',
  `fecha_registro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`iddocumento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `afcontrol`.`afiliado_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afcontrol`.`afiliado_documento` (
  `idafiliado_documento` INT(11) NOT NULL AUTO_INCREMENT,
  `clasificacion` VARCHAR(50) NULL DEFAULT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  `is_foto_perfil` INT(11) NULL DEFAULT '0',
  `fecha_registro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `afiliado_idafiliado` INT(11) NULL DEFAULT NULL,
  `documento_iddocumento` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idafiliado_documento`),
  INDEX `afiliado_idafiliado` (`afiliado_idafiliado` ASC),
  INDEX `documento_iddocumento` (`documento_iddocumento` ASC),
  INDEX `documento_iddocumento_2` (`documento_iddocumento` ASC),
  INDEX `afiliado_idafiliado_2` (`afiliado_idafiliado` ASC),
  CONSTRAINT `afiliado_documento_ibfk_1`
    FOREIGN KEY (`documento_iddocumento`)
    REFERENCES `afcontrol`.`documento` (`iddocumento`),
  CONSTRAINT `afiliado_documento_ibfk_2`
    FOREIGN KEY (`afiliado_idafiliado`)
    REFERENCES `afcontrol`.`afiliado` (`idafiliado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `afcontrol`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afcontrol`.`categoria` (
  `idcategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `afcontrol`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afcontrol`.`grupo` (
  `idgrupo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_grupo` VARCHAR(50) NULL DEFAULT NULL,
  `categoria_idcategoria` INT(11) NOT NULL,
  PRIMARY KEY (`idgrupo`),
  INDEX `fk_grupo_categoria1_idx` (`categoria_idcategoria` ASC),
  CONSTRAINT `fk_grupo_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `afcontrol`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `afcontrol`.`afiliado_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afcontrol`.`afiliado_grupo` (
  `idafiliado_grupo` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_afiliacion` DATE NULL DEFAULT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  `estado` TINYINT(1) NULL DEFAULT NULL,
  `mora` TINYINT(1) NOT NULL,
  `afiliado_idafiliado` INT(11) NOT NULL,
  `grupo_idgrupo` INT(11) NOT NULL,
  PRIMARY KEY (`idafiliado_grupo`),
  INDEX `fk_afiliado_grupo_afiliado1_idx` (`afiliado_idafiliado` ASC),
  INDEX `fk_afiliado_grupo_grupo1_idx` (`grupo_idgrupo` ASC),
  CONSTRAINT `fk_afiliado_grupo_afiliado1`
    FOREIGN KEY (`afiliado_idafiliado`)
    REFERENCES `afcontrol`.`afiliado` (`idafiliado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_afiliado_grupo_grupo1`
    FOREIGN KEY (`grupo_idgrupo`)
    REFERENCES `afcontrol`.`grupo` (`idgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `afcontrol`.`examen_medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afcontrol`.`examen_medico` (
  `idexamen_medico` INT(11) NOT NULL AUTO_INCREMENT,
  `afiliado_idafiliado` INT(11) NOT NULL,
  `fecha_examen` DATE NOT NULL,
  `peso` VARCHAR(10) NULL DEFAULT NULL,
  `estatura` VARCHAR(10) NULL DEFAULT NULL,
  `presion_arterial` VARCHAR(25) NULL DEFAULT NULL,
  `rh` VARCHAR(5) NULL DEFAULT NULL,
  `enfermedades` TEXT NULL DEFAULT NULL,
  `alergias` TEXT NULL DEFAULT NULL,
  `vacunas` TEXT NULL DEFAULT NULL,
  `medicamentos` VARCHAR(250) NULL DEFAULT NULL,
  `apto_actividad` TINYINT(1) NULL DEFAULT '1',
  `observaciones` TEXT NULL DEFAULT NULL,
  `fecha_registro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idexamen_medico`),
  INDEX `afiliado_idafiliado` (`afiliado_idafiliado` ASC),
  CONSTRAINT `examen_medico_ibfk_1`
    FOREIGN KEY (`afiliado_idafiliado`)
    REFERENCES `afcontrol`.`afiliado` (`idafiliado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `afcontrol`.`concepto_financiero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afcontrol`.`concepto_financiero` (
  `idconcepto_financiero` INT NOT NULL AUTO_INCREMENT,
  `nombre_concepto` VARCHAR(75) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idconcepto_financiero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `afcontrol`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afcontrol`.`pago` (
  `idpago` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL,
  `fecha_referencia_pago` DATE NULL,
  `valor` DOUBLE NULL,
  `fecha_registro` TIMESTAMP NULL DEFAULT now(),
  `observacion` VARCHAR(500) NULL,
  `concepto_financiero_idconcepto_financiero` INT NOT NULL,
  PRIMARY KEY (`idpago`),
  INDEX `fk_pago_concepto_financiero1_idx` (`concepto_financiero_idconcepto_financiero` ASC),
  CONSTRAINT `fk_pago_concepto_financiero1`
    FOREIGN KEY (`concepto_financiero_idconcepto_financiero`)
    REFERENCES `afcontrol`.`concepto_financiero` (`idconcepto_financiero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `afcontrol`.`recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afcontrol`.`recibo` (
  `idrecibo` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_creacion` DATE NOT NULL,
  `total_recibo` DOUBLE NOT NULL,
  `idafiliado` INT(11) NOT NULL,
  `idusuario` INT(11) NOT NULL,
  `pago_idpago` INT NOT NULL,
  PRIMARY KEY (`idrecibo`),
  INDEX `idusuario` (`idusuario` ASC),
  INDEX `idafiliado` (`idafiliado` ASC),
  INDEX `fk_recibo_pago1_idx` (`pago_idpago` ASC),
  CONSTRAINT `fk_recibo_pago1`
    FOREIGN KEY (`pago_idpago`)
    REFERENCES `afcontrol`.`pago` (`idpago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `afcontrol`.`mensualidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afcontrol`.`mensualidad` (
  `idmensualidad` INT(11) NOT NULL AUTO_INCREMENT,
  `valor_mensualidad` DOUBLE NULL DEFAULT NULL,
  `mes` INT(11) NULL DEFAULT NULL,
  `year` INT(11) NULL DEFAULT NULL,
  `observacion` VARCHAR(2000) NOT NULL,
  `fecha_registro` TIMESTAMP NULL DEFAULT now(),
  `afiliado_grupo_idafiliado_grupo` INT(11) NOT NULL,
  `pago_idpago` INT NOT NULL,
  `recibo_idrecibo` INT(11) NOT NULL,
  PRIMARY KEY (`idmensualidad`),
  INDEX `fk_mensualidad_afiliado_grupo1_idx` (`afiliado_grupo_idafiliado_grupo` ASC),
  INDEX `fk_mensualidad_pago1_idx` (`pago_idpago` ASC),
  INDEX `fk_mensualidad_recibo1_idx` (`recibo_idrecibo` ASC),
  CONSTRAINT `fk_mensualidad_afiliado_grupo1`
    FOREIGN KEY (`afiliado_grupo_idafiliado_grupo`)
    REFERENCES `afcontrol`.`afiliado_grupo` (`idafiliado_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensualidad_pago1`
    FOREIGN KEY (`pago_idpago`)
    REFERENCES `afcontrol`.`pago` (`idpago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensualidad_recibo1`
    FOREIGN KEY (`recibo_idrecibo`)
    REFERENCES `afcontrol`.`recibo` (`idrecibo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `afcontrol`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afcontrol`.`rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(45) NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `afcontrol`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afcontrol`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(256) NULL DEFAULT NULL,
  `mail` VARCHAR(100) NULL DEFAULT NULL,
  `estado` TINYINT(1) NULL,
  `rol_idrol` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_rol1_idx` (`rol_idrol` ASC),
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`rol_idrol`)
    REFERENCES `afcontrol`.`rol` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `afcontrol`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afcontrol`.`permiso` (
  `idpermiso` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL,
  `nombre_permiso` VARCHAR(75) NULL,
  PRIMARY KEY (`idpermiso`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `afcontrol`.`rol_has_permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afcontrol`.`rol_has_permiso` (
  `idrol_has_permiso` INT NOT NULL AUTO_INCREMENT,
  `rol_idrol` INT NOT NULL,
  `permiso_idpermiso` INT NOT NULL,
  `fecha_registro` DATETIME NULL,
  INDEX `fk_rol_has_permiso_permiso1_idx` (`permiso_idpermiso` ASC),
  INDEX `fk_rol_has_permiso_rol1_idx` (`rol_idrol` ASC),
  PRIMARY KEY (`idrol_has_permiso`),
  CONSTRAINT `fk_rol_has_permiso_rol1`
    FOREIGN KEY (`rol_idrol`)
    REFERENCES `afcontrol`.`rol` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rol_has_permiso_permiso1`
    FOREIGN KEY (`permiso_idpermiso`)
    REFERENCES `afcontrol`.`permiso` (`idpermiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `afcontrol`.`documento_has_recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afcontrol`.`documento_has_recibo` (
  `iddocumento_has_recibo` INT NOT NULL AUTO_INCREMENT,
  `documento_iddocumento` INT(11) NOT NULL,
  `recibo_idrecibo` INT(11) NOT NULL,
  INDEX `fk_documento_has_recibo_recibo1_idx` (`recibo_idrecibo` ASC),
  INDEX `fk_documento_has_recibo_documento1_idx` (`documento_iddocumento` ASC),
  PRIMARY KEY (`iddocumento_has_recibo`),
  CONSTRAINT `fk_documento_has_recibo_documento1`
    FOREIGN KEY (`documento_iddocumento`)
    REFERENCES `afcontrol`.`documento` (`iddocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documento_has_recibo_recibo1`
    FOREIGN KEY (`recibo_idrecibo`)
    REFERENCES `afcontrol`.`recibo` (`idrecibo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `afcontrol`.`afiliado_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afcontrol`.`afiliado_has_usuario` (
  `idafiliado_has_usuario` INT NOT NULL AUTO_INCREMENT,
  `afiliado_idafiliado` INT(11) NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  `tipo_relacion` VARCHAR(45) NULL,
  INDEX `fk_afiliado_has_usuario_usuario1_idx` (`usuario_idusuario` ASC),
  INDEX `fk_afiliado_has_usuario_afiliado1_idx` (`afiliado_idafiliado` ASC),
  PRIMARY KEY (`idafiliado_has_usuario`),
  CONSTRAINT `fk_afiliado_has_usuario_afiliado1`
    FOREIGN KEY (`afiliado_idafiliado`)
    REFERENCES `afcontrol`.`afiliado` (`idafiliado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_afiliado_has_usuario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `afcontrol`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
